/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * cadUsuario.java
 *
 * Created on 06/05/2011, 15:23:49
 */
package petshop;

//import java.sql.Statement;
import java.sql.*;
import javax.swing.*;
import java.sql.ResultSet;
import java.lang.String;

/**
 *
 * @author USER
 */
public class cadUsuario extends javax.swing.JFrame {
    private Object request;

    /** Creates new form cadUsuario */
    public cadUsuario() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        usuarioSenha = new javax.swing.JPasswordField();
        usuarioNome = new javax.swing.JTextField();
        usuarioNivel = new javax.swing.JTextField();
        usuarioCod = new javax.swing.JTextField();
        usuarioGravar = new javax.swing.JButton();
        usuarioAlterar = new javax.swing.JButton();
        usuarioExcluir = new javax.swing.JButton();
        usuarioLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Usuários");

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 36));
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Cadastro de Usuários no Sistema");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(117, 117, 117))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jLabel2.setText("Código :");

        jLabel3.setText("Usuário: ");

        jLabel4.setText("Senha : ");

        jLabel5.setText("Nível de Acesso: ");

        usuarioCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioCodActionPerformed(evt);
            }
        });
        usuarioCod.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                usuarioCodFocusLost(evt);
            }
        });

        usuarioGravar.setIcon(new javax.swing.ImageIcon("D:\\Diversos\\Icons\\gravar3.png")); // NOI18N
        usuarioGravar.setText("Gravar");
        usuarioGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioGravarActionPerformed(evt);
            }
        });

        usuarioAlterar.setIcon(new javax.swing.ImageIcon("D:\\Diversos\\Icons\\edit-icon.png")); // NOI18N
        usuarioAlterar.setText("Alterar");

        usuarioExcluir.setIcon(new javax.swing.ImageIcon("D:\\Diversos\\Icons\\delete-user-icon.png")); // NOI18N
        usuarioExcluir.setText("Excluir");

        usuarioLimpar.setIcon(new javax.swing.ImageIcon("D:\\Diversos\\Icons\\ico-limpeza.png")); // NOI18N
        usuarioLimpar.setText("Limpar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usuarioNome, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usuarioCod, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usuarioNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(usuarioSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(325, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(usuarioGravar)
                .addGap(18, 18, 18)
                .addComponent(usuarioAlterar)
                .addGap(18, 18, 18)
                .addComponent(usuarioExcluir)
                .addGap(18, 18, 18)
                .addComponent(usuarioLimpar)
                .addContainerGap(287, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(usuarioNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usuarioCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(usuarioSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usuarioNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuarioGravar)
                    .addComponent(usuarioAlterar)
                    .addComponent(usuarioExcluir)
                    .addComponent(usuarioLimpar))
                .addContainerGap(175, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-800)/2, (screenSize.height-600)/2, 800, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioGravarActionPerformed

         
        
    }//GEN-LAST:event_usuarioGravarActionPerformed

         private void usuarioCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioCodActionPerformed
             
             
                
                
             
         }//GEN-LAST:event_usuarioCodActionPerformed

         private void usuarioCodFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usuarioCodFocusLost
             
             String url = "jdbc:postgresql://localhost:5432/petshop";
                String driverbancodados = "org.postgresql.Driver";
                Connection con;
                String user= "postgres";
                String pass= "postgres";
                
                if(!usuarioCod.getText().equalsIgnoreCase(" ")){

                String comando = "SELECT * FROM login WHERE log_usuario = '" + usuarioCod.getText()+ "'";

                Statement stmt;
                try {
                Class.forName(driverbancodados);
                } catch(java.lang.ClassNotFoundException e1) {
                JOptionPane.showMessageDialog(null, "Problema na carga do driver do banco de dados! Chame o Analista de Sistemas!");
                }

                try{

                con = DriverManager.getConnection(url, user, pass);
                Statement sent= con.createStatement();
                ResultSet result = sent.executeQuery(comando);
                if(result.next())
                {
                usuarioCod.setText(result.getString("log_codigo"));
                usuarioNivel.setText(result.getString("log_nivelacesso"));
                usuarioNome.setText(result.getString("log_usuario"));
                usuarioSenha.setText(result.getString("log_senha"));
                }
                else
                {
                JOptionPane.showMessageDialog(null, "Código não cadastrado! Pode usar para um novo cadastro!");
                usuarioNivel.setText("");
                usuarioNome.setText("");
                usuarioSenha.setText("");
                
                sent.close();
                con.close();
                }
                }
                catch(SQLException ex)
                {
                System.out.println("Erro de consulta ao sair do campo");
                }

                

                }
         
         }//GEN-LAST:event_usuarioCodFocusLost

    
         
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new cadUsuario().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton usuarioAlterar;
    private javax.swing.JTextField usuarioCod;
    private javax.swing.JButton usuarioExcluir;
    private javax.swing.JButton usuarioGravar;
    private javax.swing.JButton usuarioLimpar;
    private javax.swing.JTextField usuarioNivel;
    private javax.swing.JTextField usuarioNome;
    private javax.swing.JPasswordField usuarioSenha;
    // End of variables declaration//GEN-END:variables
}
