/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Cliente.java
 *
 * Created on 02/05/2011, 20:59:42
 */
package petshop;

import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.omg.CORBA.PUBLIC_MEMBER;
import utilitarios.conexao;

/**
 *
 * @author udp.3019145605
 */
public class cliente extends javax.swing.JFrame {
    
    conexao con_cliente;
    String ordenacao = "nome_cliente";
    private Object tf_fotos;
    private Object label_foto;

    public cliente() {
        initComponents();
        con_cliente = new conexao();
        con_cliente.conecta();
        jTable1.setAutoCreateRowSorter(true);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        cod_cliente = new javax.swing.JTextField();
        nome_cliente = new javax.swing.JTextField();
        data = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cpf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rg = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        profissao = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        rua = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        numero = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        bairro = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cidade = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cep = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        contato1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        fone1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        contato2 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        fone2 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        fone = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        celular = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        sexo = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        tf_pesquisa = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        uf = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Clientes");

        cod_cliente.setText(" ");
        cod_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cod_clienteActionPerformed(evt);
            }
        });
        cod_cliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cod_clienteFocusLost(evt);
            }
        });

        nome_cliente.setText(" ");

        data.setText(" ");

        jLabel2.setText("Nome:");

        jLabel1.setText("Código:");

        jLabel6.setText("Data Nascimento:");

        jLabel7.setText("CPF:");

        cpf.setText(" ");

        jLabel8.setText("Sexo:");

        jLabel4.setText("RG:");

        rg.setText(" ");

        jLabel5.setText("Profissão");

        profissao.setText(" ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel9.setText("ENDEREÇO:");

        jLabel10.setText("Rua:");

        rua.setText(" ");

        jLabel11.setText("Número:");

        numero.setText(" ");

        jLabel12.setText("Bairro:");

        bairro.setText(" ");
        bairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bairroActionPerformed(evt);
            }
        });

        jLabel13.setText("Cidade:");

        cidade.setText(" ");

        jLabel14.setText("UF:");

        jLabel15.setText("CEP:");

        cep.setText(" ");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel16.setText("CONTATO:");

        jLabel17.setText("Contato:");

        contato1.setText(" ");
        contato1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contato1ActionPerformed(evt);
            }
        });

        jLabel18.setText("Fone:");

        fone1.setText(" ");

        jLabel19.setText("Contato:");

        contato2.setText(" ");

        jLabel20.setText("Fone:");

        fone2.setText(" ");

        jLabel23.setText("Fone:");

        fone.setText(" ");

        jLabel24.setText("Celular:");

        celular.setText(" ");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/gravar3.png"))); // NOI18N
        jButton1.setToolTipText("Gravar Registro");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/ico-limpeza.png"))); // NOI18N
        jButton2.setToolTipText("Limpar Campos Registro");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/delete-user-icon.png"))); // NOI18N
        jButton3.setToolTipText("Excluir Registro");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/edit-icon.png"))); // NOI18N
        jButton4.setToolTipText("Alterar/Editar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel21.setText("E-mail:");

        email.setText(" ");

        sexo.setText(" ");

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 24));
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("Cadastro de Clientes");
        jLabel3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(538, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(494, 494, 494))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel22.setText("DADOS PESSOAIS:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Endereço", "Numero", "Bairro", "Cidade", "Cep", "Telefone", "Celular", "CPF", "RG", "Sexo", "Data Nascimento", "Email", "Profissão", "Contato 1", "Telefone Contato 1", "Contato 2", "Telefone Contato 2", "UF"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.setBackground(java.awt.Color.white);

        jLabel25.setText("Pesquisar");

        tf_pesquisa.setToolTipText("Pesquisar Cadastro");

        jButton5.setText("Filtrar na Grade");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Código");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setSelected(true);
        jRadioButton2.setText("Nome");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jRadioButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(tf_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        uf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MS", "MT", "SP", "RJ", "PR", "MG", "DF" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel22))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(cod_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addComponent(nome_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel6)
                .addGap(5, 5, 5)
                .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel4)
                .addGap(12, 12, 12)
                .addComponent(rg, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel7)
                .addGap(7, 7, 7)
                .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel8)
                .addGap(10, 10, 10)
                .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel5)
                .addGap(4, 4, 4)
                .addComponent(profissao, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel21)
                .addGap(4, 4, 4)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1179, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel9))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(rua, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel11)
                .addGap(4, 4, 4)
                .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel12)
                .addGap(10, 10, 10)
                .addComponent(bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel13)
                .addGap(4, 4, 4)
                .addComponent(cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel14)
                .addGap(4, 4, 4)
                .addComponent(uf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(cep, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel23)
                .addGap(10, 10, 10)
                .addComponent(fone, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel24)
                .addGap(4, 4, 4)
                .addComponent(celular, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 1179, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(10, 10, 10)
                        .addComponent(contato1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel18)
                        .addGap(10, 10, 10)
                        .addComponent(fone1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(10, 10, 10)
                        .addComponent(contato2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20)
                        .addGap(10, 10, 10)
                        .addComponent(fone2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jButton1)
                        .addGap(6, 6, 6)
                        .addComponent(jButton4)
                        .addGap(10, 10, 10)
                        .addComponent(jButton3)
                        .addGap(6, 6, 6)
                        .addComponent(jButton2)))
                .addGap(182, 182, 182)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1149, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(cod_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(nome_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel8))
                    .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5))
                    .addComponent(profissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel21))
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel9)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel10))
                    .addComponent(rua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel11))
                    .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel12))
                    .addComponent(bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel13))
                    .addComponent(cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel14))
                    .addComponent(uf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel15))
                    .addComponent(cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel23))
                    .addComponent(fone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel24))
                    .addComponent(celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel17))
                            .addComponent(contato1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel18))
                            .addComponent(fone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel19))
                            .addComponent(contato2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel20))
                            .addComponent(fone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton4)
                            .addComponent(jButton3)
                            .addComponent(jButton2)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1280)/2, (screenSize.height-800)/2, 1280, 800);
    }// </editor-fold>//GEN-END:initComponents

    private void contato1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contato1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contato1ActionPerformed
    
    private void bairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bairroActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
              // TODO add your handling code here:
        String url = "jdbc:postgresql://localhost:5432/petshop";
    String driverbancodados = "org.postgresql.Driver";
    Connection con;
    String usuario= "postgres";
    String senha= "postgres";

    String comando = "INSERT INTO cliente VALUES (" +
            cod_cliente.getText() + ",'" +
            nome_cliente.getText() + "','"+
            data.getText()+"','"+
            rg.getText()+"','"+
            cpf.getText()+"','"+
            sexo.getText()+"','"+
            profissao.getText()+"','"+
            rua.getText()+"','"+
            numero.getText()+"','"+
            bairro.getText()+"','"+
            cidade.getText()+"','"+
            uf.getSelectedItem()+"','"+
            cep.getText()+"','"+
            fone.getText()+"','"+
            celular.getText()+"','"+
            email.getText()+"','"+
            contato1.getText()+"','"+
            fone1.getText()+"','"+
            contato2.getText()+"','"+
            fone2.getText()+"')";
    
   


	Statement stmt;
    try {
            Class.forName(driverbancodados);
    } 		catch(java.lang.ClassNotFoundException e1) {
        		JOptionPane.showMessageDialog(null, "Problema na carga do driver do banco de dados! Chame o Analista de Sistemas!");
    }

    try {
        con = DriverManager.getConnection(url, usuario, senha);
        stmt = con.createStatement();
        int rs = stmt.executeUpdate(comando);
        JOptionPane.showMessageDialog(null, "Cadastro de Cliente Efetuado com Sucesso!");

        stmt.close();
        con.close();

    cod_cliente.setText("");
    nome_cliente.setText("");
    data.setText("");
    rg.setText("");
    cpf.setText("");
    sexo.setText("");
    profissao.setText("");
    rua.setText("");
    numero.setText("");
    bairro.setText("");
    cidade.setText("");
    uf.setSelectedItem("");
    cep.setText("");
    fone.setText("");
    celular.setText("");
    email.setText("");
    contato1.setText("");
    fone1.setText("");
    contato2.setText("");
    fone2.setText("");


                    // Posiciona o cursor no jTextField1
                    cod_cliente.requestFocus();


        } catch(SQLException ex) {
          JOptionPane.showMessageDialog(null, "Problemas na conexão com o banco de dados!");

}


                                         
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void cod_clienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cod_clienteFocusLost
        // TODO add your handling code here:
        String url = "jdbc:postgresql://localhost:5432/petshop";
        String driverbancodados = "org.postgresql.Driver";
        Connection con;
        String usuario = "postgres";
        String senha = "postgres";
        
        
        if (!cod_cliente.getText().equalsIgnoreCase("")) {
            
            String comando = "SELECT * FROM cliente WHERE id_cliente = " + cod_cliente.getText();
            
            Statement stmt;
            try {
                Class.forName(driverbancodados);
            } catch (java.lang.ClassNotFoundException e1) {
                JOptionPane.showMessageDialog(null, "Problema na carga do driver do banco de dados! Chame o Analista de Sistemas!");
            }
            try {
                con = DriverManager.getConnection(url, usuario, senha);
                Statement sent = con.createStatement();
                ResultSet result = sent.executeQuery(comando);
                if (result.next()) {
                    cod_cliente.setText(result.getString("id_cliente"));
                    nome_cliente.setText(result.getString("nome_cliente"));
                    data.setText(result.getString("dt_nasc_cliente"));
                    rg.setText(result.getString("rg_insc_cliente"));
                    cpf.setText(result.getString("cpf_cnpj_cliente"));
                    sexo.setText(result.getString("sexo_cliente"));
                    profissao.setText(result.getString("profissao_cliente"));
                    rua.setText(result.getString("endereco_cliente"));
                    numero.setText(result.getString("numero_cliente"));
                    bairro.setText(result.getString("bairro_cliente"));
                    cidade.setText(result.getString("cidade_cliente"));
                    uf.setSelectedItem(result.getString("uf_cliente"));
                    cep.setText(result.getString("cep_cliente"));
                    fone.setText(result.getString("fone_cliente"));
                    celular.setText(result.getString("celular_cliente"));
                    email.setText(result.getString("email_cliente"));
                    contato1.setText(result.getString("contato1_cliente"));
                    fone1.setText(result.getString("fone1_cliente"));
                    contato2.setText(result.getString("contato2_cliente"));
                    fone2.setText(result.getString("fone2_cliente"));
                    
                } else {
                    JOptionPane.showMessageDialog(null, "Código não cadastrado! Pode usar para um novo cadastro!");
                    nome_cliente.setText("");
                    data.setText("");
                    rg.setText("");
                    cpf.setText("");
                    sexo.setText("");
                    profissao.setText("");
                    rua.setText("");
                    numero.setText("");
                    bairro.setText("");
                    cidade.setText("");
                    uf.setSelectedItem("");
                    cep.setText("");
                    fone.setText("");
                    celular.setText("");
                    email.setText("");
                    contato1.setText("");
                    fone1.setText("");
                    contato2.setText("");
                    fone2.setText("");
                }
                sent.close();
                con.close();
            } catch (SQLException ex) {
                System.out.println("Erro de consulta ao sair do campo");
            }
        }
    }//GEN-LAST:event_cod_clienteFocusLost
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String url = "jdbc:postgresql://localhost:5432/petshop";
        String driverbancodados = "org.postgresql.Driver";
        Connection con;
        String usuario = "postgres";
        String senha = "postgres";
        
        String comando = "UPDATE cliente  set nome_cliente = '" + nome_cliente.getText()
                + "', dt_nasc_cliente = '" + data.getText()
                + "', rg_insc_cliente = '" + rg.getText()
                + "', cpf_cnpj_cliente = '" + cpf.getText()
                + "', sexo_cliente = '" + sexo.getText()
                + "', profissao_cliente = '" + profissao.getText()
                + "', endereco_cliente = '" + rua.getText()
                + "', numero_cliente = '" + numero.getText()
                + "', bairro_cliente = '" + bairro.getText()
                + "', cidade_cliente = '" + cidade.getText()
                + "', uf_cliente = '" + uf.getSelectedItem()
                + "', cep_cliente = '" + cep.getText()
                + "', fone_cliente = '" + fone.getText()
                + "', celular_cliente = '" + celular.getText()
                + "', email_cliente = '" + email.getText()
                + "', contato1_cliente = '" + contato1.getText()
                + "', fone1_cliente = '" + fone1.getText()
                + "', contato2_cliente = '" + contato2.getText()
                + "', fone2_cliente = '" + fone2.getText()
                + "' WHERE id_cliente = " + cod_cliente.getText();
        
        Statement stmt;
        try {
            Class.forName(driverbancodados);
        } catch (java.lang.ClassNotFoundException e1) {
            JOptionPane.showMessageDialog(null, "Problema na carga do driver do banco de dados! Chame o Analista de Sistemas!");
        }
        
        try {
            con = DriverManager.getConnection(url, usuario, senha);
            stmt = con.createStatement();
            int rs = stmt.executeUpdate(comando);
            JOptionPane.showMessageDialog(null, "Alteração com Sucesso!");
            stmt.close();
            con.close();
            
            nome_cliente.setText("");
            data.setText("");
            rg.setText("");
            cpf.setText("");
            sexo.setText("");
            profissao.setText("");
            rua.setText("");
            numero.setText("");
            bairro.setText("");
            cidade.setText("");
            uf.setSelectedItem("");
            cep.setText("");
            fone.setText("");
            celular.setText("");
            email.setText("");
            contato1.setText("");
            fone1.setText("");
            contato2.setText("");
            fone2.setText("");
            
            cod_cliente.requestFocus();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Problemas na conexão com o banco de dados!");
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String url = "jdbc:postgresql://localhost:5432/petshop";
        String driverbancodados = "org.postgresql.Driver";
        Connection con;
        String usuario = "postgres";
        String senha = "postgres";
        
        
        int opcao;
        Object[] botao = {"SIM", "NÃO"};
        
        opcao = JOptionPane.showOptionDialog(null, "Deseja realmente excluir?", "EXCLUIR",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, botao, botao[0]);
        
        if (opcao == JOptionPane.YES_OPTION) {
            
            
            
            String comando = "DELETE FROM cliente  WHERE id_cliente = "
                    + cod_cliente.getText();
            
            Statement stmt;
            try {
                Class.forName(driverbancodados);
            } catch (java.lang.ClassNotFoundException e1) {
                JOptionPane.showMessageDialog(null, "Problema na carga do driver do banco de dados! Chame o Analista de Sistemas!");
            }
            
            try {
                con = DriverManager.getConnection(url, usuario, senha);
                stmt = con.createStatement();
                int rs = stmt.executeUpdate(comando);
                JOptionPane.showMessageDialog(null, "Exclusão Efetuada com Sucesso!");
                
                stmt.close();
                con.close();
                cod_cliente.setText("");
                nome_cliente.setText("");
                data.setText("");
                rg.setText("");
                cpf.setText("");
                sexo.setText("");
                profissao.setText("");
                rua.setText("");
                numero.setText("");
                bairro.setText("");
                cidade.setText("");
                uf.setSelectedItem("");
                cep.setText("");
                fone.setText("");
                celular.setText("");
                email.setText("");
                contato1.setText("");
                fone1.setText("");
                contato2.setText("");
                fone2.setText("");

                // Posiciona o cursor no jTextField1
                cod_cliente.requestFocus();
                
                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Problemas na conexão com o banco de dados!");
                
            }
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        cod_cliente.setText("");
        nome_cliente.setText("");
        data.setText("");
        rg.setText("");
        cpf.setText("");
        sexo.setText("");
        profissao.setText("");
        rua.setText("");
        numero.setText("");
        bairro.setText("");
        cidade.setText("");
        uf.setSelectedItem("");
        cep.setText("");
        fone.setText("");
        celular.setText("");
        email.setText("");
        contato1.setText("");
        fone1.setText("");
        contato2.setText("");
        fone2.setText("");
        cod_cliente.requestFocus();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        con_cliente.executeSQL("select * from cliente where nome_cliente like '" + tf_pesquisa.getText() + "%' order by " + ordenacao);        
        preencher_jtable();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed
    
    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        ordem_visualizacao("nome_cliente");// TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed
    
    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        ordem_visualizacao("id_cliente");// TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed
    
    private void cod_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cod_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cod_clienteActionPerformed
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int linha = jTable1.getSelectedRow();
        cod_cliente.setText(jTable1.getValueAt(linha, 0).toString());
        nome_cliente.setText(jTable1.getValueAt(linha, 1).toString());
        rua.setText(jTable1.getValueAt(linha, 2).toString());
        numero.setText(jTable1.getValueAt(linha, 3).toString());
        bairro.setText(jTable1.getValueAt(linha, 4).toString());
        cidade.setText(jTable1.getValueAt(linha, 5).toString());
        cep.setText(jTable1.getValueAt(linha, 6).toString());
        fone.setText(jTable1.getValueAt(linha, 7).toString());
        celular.setText(jTable1.getValueAt(linha, 8).toString());
        cpf.setText(jTable1.getValueAt(linha, 9).toString());
        rg.setText(jTable1.getValueAt(linha, 10).toString());
        sexo.setText(jTable1.getValueAt(linha, 11).toString());
        data.setText(jTable1.getValueAt(linha, 12).toString());
        email.setText(jTable1.getValueAt(linha, 13).toString());
        profissao.setText(jTable1.getValueAt(linha, 14).toString());
        contato1.setText(jTable1.getValueAt(linha, 15).toString());
        fone1.setText(jTable1.getValueAt(linha, 16).toString());
        contato2.setText(jTable1.getValueAt(linha, 17).toString());        
        fone2.setText(jTable1.getValueAt(linha, 18).toString());
        uf.setSelectedItem(jTable1.getValueAt(linha, 19));
        
mostrar_dados();        
        
        
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            @Override
            public void run() {
                new cliente().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bairro;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField celular;
    private javax.swing.JTextField cep;
    private javax.swing.JTextField cidade;
    private javax.swing.JTextField cod_cliente;
    private javax.swing.JTextField contato1;
    private javax.swing.JTextField contato2;
    private javax.swing.JTextField cpf;
    private javax.swing.JTextField data;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fone;
    private javax.swing.JTextField fone1;
    private javax.swing.JTextField fone2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nome_cliente;
    private javax.swing.JTextField numero;
    private javax.swing.JTextField profissao;
    private javax.swing.JTextField rg;
    private javax.swing.JTextField rua;
    private javax.swing.JTextField sexo;
    private javax.swing.JTextField tf_pesquisa;
    private javax.swing.JComboBox uf;
    // End of variables declaration//GEN-END:variables

    public void mostrar_dados() {
        try {
            cod_cliente.setText(con_cliente.resultset.getString("id_cliente"));
            nome_cliente.setText(con_cliente.getString("nome_cliente"));
            data.setText(con_cliente.getString("dt_nasc_cliente"));
            rg.setText(con_cliente.getString("rg_insc_cliente"));
            cpf.setText(con_cliente.getString("cpf_cnpj_cliente"));
            sexo.setText(con_cliente.getString("sexo_cliente"));
            profissao.setText(con_cliente.getString("profissao_cliente"));
            rua.setText(con_cliente.getString("endereco_cliente"));
            numero.setText(con_cliente.getString("numero_cliente"));
            bairro.setText(con_cliente.getString("bairro_cliente"));
            cidade.setText(con_cliente.getString("cidade_cliente"));
            uf.setSelectedItem(con_cliente.resultset.getString("uf_cliente"));
            cep.setText(con_cliente.getString("cep_cliente"));
            fone.setText(con_cliente.getString("fone_cliente"));
            celular.setText(con_cliente.getString("celular_cliente"));
            email.setText(con_cliente.getString("email_cliente"));
            contato1.setText(con_cliente.getString("contato1_cliente"));
            fone1.setText(con_cliente.getString("fone1_cliente"));
            contato2.setText(con_cliente.getString("contato2_cliente"));
            fone2.setText(con_cliente.getString("fone2_cliente"));
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro =" + erro);            
        }
    }
    
    public void preencher_jtable() {
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(60);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(20);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(90);
        jTable1.getColumnModel().getColumn(6).setPreferredWidth(40);
        jTable1.getColumnModel().getColumn(7).setPreferredWidth(40);
        
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setNumRows(0);
        
        try {
            
            while (con_cliente.resultset.next()) {
                modelo.addRow(new Object[]{con_cliente.resultset.getString("id_cliente"),
                            con_cliente.resultset.getString("nome_cliente"),
                            con_cliente.resultset.getString("endereco_cliente"),
                            con_cliente.resultset.getString("numero_cliente"),
                            con_cliente.resultset.getString("bairro_cliente"),
                            con_cliente.resultset.getString("cidade_cliente"),
                            con_cliente.resultset.getString("cep_cliente"),
                            con_cliente.resultset.getString("fone_cliente"),
                            con_cliente.resultset.getString("celular_cliente"),
                            con_cliente.resultset.getString("cpf_cnpj_cliente"),
                            con_cliente.resultset.getString("rg_insc_cliente"),
                            con_cliente.resultset.getString("sexo_cliente"),
                            con_cliente.resultset.getString("dt_nasc_cliente"),
                            con_cliente.resultset.getString("email_cliente"),
                            con_cliente.resultset.getString("profissao_cliente"),
                            con_cliente.resultset.getString("contato1_cliente"),
                            con_cliente.resultset.getString("fone1_cliente"),
                            con_cliente.resultset.getString("contato2_cliente"),
                            con_cliente.resultset.getString("fone2_cliente"),
                            con_cliente.resultset.getString("uf_cliente")});
            }
            
            
            
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "Erro ao listar no JTable " + erro);
        }        
    }

    public void ordem_visualizacao(String Ordem) {
        ordenacao = Ordem;
        con_cliente.executeSQL("select * from cliente  order by " + ordenacao);        
        preencher_jtable();
        
        try {
            con_cliente.resultset.first();
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "Erro na ordenação dos dados " + erro);
        }
        
        
        
    }
}
