/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * fornecedor.java
 *
 * Created on 06/05/2011, 17:42:36
 */

package petshop;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author udp.3019145605
 */
public class fornecedor extends javax.swing.JFrame {

    /** Creates new form fornecedor */
    public fornecedor() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        cnpj = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        razao_social = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rua = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        numero = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        bairro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fone = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("CNPJ:");

        cnpj.setText(" ");
        cnpj.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cnpjFocusLost(evt);
            }
        });

        jLabel3.setText("RAZÃO SOCIAL:");

        razao_social.setText("  ");

        jLabel4.setText("RUA:");

        rua.setText(" ");

        jLabel5.setText("NÚMERO:");

        numero.setText(" ");

        jLabel6.setText("BAIRRO:");

        bairro.setText(" ");
        bairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bairroActionPerformed(evt);
            }
        });

        jLabel7.setText("FONE:");

        fone.setText(" ");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/gravar3.png"))); // NOI18N
        jButton1.setToolTipText("Gravar Registro");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/edit-icon.png"))); // NOI18N
        jButton2.setToolTipText("Editar/Alterar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/delete-user-icon.png"))); // NOI18N
        jButton3.setToolTipText("Excluir Registro");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/ico-limpeza.png"))); // NOI18N
        jButton4.setToolTipText("Limpar todos Campos");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Fornecedor");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(546, 546, 546)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(558, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(razao_social, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bairro)
                                    .addComponent(rua, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fone, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)))
                .addContainerGap(704, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(razao_social, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(324, 324, 324))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1280)/2, (screenSize.height-800)/2, 1280, 800);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String url = "jdbc:postgresql://localhost:5432/petshop";
    String driverbancodados = "org.postgresql.Driver";
    Connection con;
    String usuario= "postgres";
    String senha= "postgres";

    String comando = "INSERT INTO fornecedor VALUES (" +
            cnpj.getText() + ",'" +
            razao_social.getText() + "','"+
            rua.getText()+"',"+
            numero.getText()+",'"+
            bairro.getText()+"','"+
            fone.getText()+"')";



	Statement stmt;
    try {
            Class.forName(driverbancodados);
    } 		catch(java.lang.ClassNotFoundException e1) {
        		JOptionPane.showMessageDialog(null, "Problema na carga do driver do banco de dados! Chame o Analista de Sistemas!");
    }

    try {
        con = DriverManager.getConnection(url, usuario, senha);
        stmt = con.createStatement();
        int rs = stmt.executeUpdate(comando);
        JOptionPane.showMessageDialog(null, "Cadastro Efetuado com Sucesso!");

        stmt.close();
        con.close();

            cnpj.setText("");
            razao_social.setText("");
            rua.setText("");
            numero.setText("");
            bairro.setText("");
            fone.setText("");
                    
            cnpj.requestFocus();


        } catch(SQLException ex) {
          JOptionPane.showMessageDialog(null, "Problemas na conexão com o banco de dados!");

}

    }//GEN-LAST:event_jButton1ActionPerformed

    private void cnpjFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cnpjFocusLost
        // TODO add your handling code here:
         String url = "jdbc:postgresql://localhost:5432/petshop";
    String driverbancodados = "org.postgresql.Driver";
    Connection con;
    String usuario= "postgres";
    String senha= "postgres";


        if (!cnpj.getText().equalsIgnoreCase("")){

    String comando = "SELECT * FROM fornecedor " +
            "WHERE id_fornecedor = " + cnpj.getText() ;

    Statement stmt;
    try {
            Class.forName(driverbancodados);
    } catch(java.lang.ClassNotFoundException e1) {
        JOptionPane.showMessageDialog(null, "Problema na carga do driver do banco de dados! Chame o Analista de Sistemas!");
    }
    try
{
        con = DriverManager.getConnection(url, usuario, senha);
        Statement sent= con.createStatement();
        ResultSet result = sent.executeQuery(comando);
        if(result.next())
        {
                cnpj.setText(result.getString("id_fornecedor"));
                razao_social.setText(result.getString("nome_fornecedor"));
                rua.setText(result.getString("endereco_fornecedor"));
                numero.setText(result.getString("numero_fornecedor"));
                bairro.setText(result.getString("bairro_fornecedor"));
                fone.setText(result.getString("telefone_fornecedor"));


        }
        else
        {
        JOptionPane.showMessageDialog(null, "Código não cadastrado! Pode usar para um novo cadastro!");
        
            razao_social.setText("");
            rua.setText("");
            numero.setText("");
            bairro.setText("");
            fone.setText("");
                    }
                    sent.close();
                    con.close();
            }
            catch(SQLException ex)
            {
                    System.out.println("Erro de consulta ao sair do campo");
            }
    }

    }//GEN-LAST:event_cnpjFocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String url = "jdbc:postgresql://localhost:5432/petshop";
    String driverbancodados = "org.postgresql.Driver";
    Connection con;
    String usuario= "postgres";
    String senha= "postgres";

        String comando = "UPDATE fornecedor  set nome_fornecedor = '"+razao_social.getText() +
                "', endereco_fornecedor = '"+rua.getText() +
                "', numero_fornecedor = '"+numero.getText() +
                "', bairro_fornecedor = '"+bairro.getText() +
                "', telefone_fornecedor = '"+fone.getText() +
                "' WHERE id_fornecedor = "+cnpj.getText();

	Statement stmt;
	try {Class.forName(driverbancodados);  }
		catch(java.lang.ClassNotFoundException e1) {JOptionPane.showMessageDialog(null, "Problema na carga do driver do banco de dados! Chame o Analista de Sistemas!");}

	try { con = DriverManager.getConnection(url, usuario, senha);
	stmt = con.createStatement();
	int rs = stmt.executeUpdate(comando);
	JOptionPane.showMessageDialog(null, "Alteração realizada com Sucesso!");
	stmt.close();
	con.close();

            razao_social.setText("");
            rua.setText("");
            numero.setText("");
            bairro.setText("");
            fone.setText("");
            cnpj.requestFocus();
        }

		catch(SQLException ex) { JOptionPane.showMessageDialog(null, "Problemas na conexão com o banco de dados!");  }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String url = "jdbc:postgresql://localhost:5432/petshop";
    String driverbancodados = "org.postgresql.Driver";
    Connection con;
    String usuario= "postgres";
    String senha= "postgres";


        int opcao;
       		Object[] botao={"SIM","NÃO"};

        opcao=JOptionPane.showOptionDialog(null,"Deseja realmente excluir?","EXCLUIR",
           JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,botao,botao[0]);

         if (opcao==JOptionPane.YES_OPTION){



        String comando = "DELETE FROM fornecedor  WHERE id_fornecedor = " +
                cnpj.getText();

        Statement stmt;
        try {
                Class.forName(driverbancodados);
        } catch(java.lang.ClassNotFoundException e1) {
        JOptionPane.showMessageDialog(null, "Problema na carga do driver do banco de dados! Chame o Analista de Sistemas!");
        }

        try {
            con = DriverManager.getConnection(url, usuario, senha);
            stmt = con.createStatement();
            int rs = stmt.executeUpdate(comando);
            JOptionPane.showMessageDialog(null, "Exclusão Efetuada com Sucesso!");

            stmt.close();
            con.close();
            cnpj.setText("");
            razao_social.setText("");
            rua.setText("");
            numero.setText("");
            bairro.setText("");
            fone.setText("");


                // Posiciona o cursor no jTextField1
               cnpj.requestFocus();


            } catch(SQLException ex) {
      JOptionPane.showMessageDialog(null, "Problemas na conexão com o banco de dados!");

    }}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        cnpj.setText("");
        razao_social.setText("");
        rua.setText("");
        numero.setText("");
        bairro.setText("");
        fone.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void bairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bairroActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bairro;
    private javax.swing.JTextField cnpj;
    private javax.swing.JTextField fone;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField numero;
    private javax.swing.JTextField razao_social;
    private javax.swing.JTextField rua;
    // End of variables declaration//GEN-END:variables

}
